from __future__ import annotations

PRACTICE_TESTS = [
    {
        "id": 1,
        "topic": "Task Framing",
        "difficulty": "Easy",
        "learning_type": "General ML",
        "question_en": "You have a table with customer features and a column `churn` showing whether the customer left. What ML task is this?",
        "question_ru": "Есть таблица с признаками клиентов и колонка `churn`, которая показывает, ушёл клиент или нет. Какой это тип ML-задачи?",
        "hint_en": "There is a target variable and it is categorical.",
        "hint_ru": "Есть целевая переменная, и она категориальная.",
        "answer_en": "This is supervised learning, specifically binary classification, because we predict a category: churn or no churn.",
        "answer_ru": "Это обучение с учителем, а именно бинарная классификация, потому что мы предсказываем категорию: клиент ушёл или не ушёл.",
        "mini_task_en": "Write a 6-step pipeline for a binary classification task.",
        "mini_task_ru": "Напиши пайплайн из 6 шагов для задачи бинарной классификации.",
    },
    {
        "id": 2,
        "topic": "Task Framing",
        "difficulty": "Easy",
        "learning_type": "General ML",
        "question_en": "You have user behavior data but no target column. You want to find groups of similar users. What ML approach should you start with?",
        "question_ru": "Есть данные о поведении пользователей, но нет target. Нужно найти группы похожих пользователей. С какого ML-подхода начать?",
        "hint_en": "No target usually means unsupervised learning.",
        "hint_ru": "Если target нет, часто это обучение без учителя.",
        "answer_en": "Start with unsupervised learning, especially clustering. A simple baseline approach is scaling features and trying K-Means with several values of k.",
        "answer_ru": "Начать нужно с обучения без учителя, особенно с кластеризации. Базовый подход: масштабировать признаки и попробовать K-Means с разными k.",
        "mini_task_en": "Create a checklist for a clustering task.",
        "mini_task_ru": "Составь чек-лист для задачи кластеризации.",
    },
    {
        "id": 3,
        "topic": "Data Leakage",
        "difficulty": "Medium",
        "learning_type": "Supervised Learning",
        "question_en": "What is wrong with fitting StandardScaler on the full dataset before train/test split?",
        "question_ru": "Что не так, если обучить StandardScaler на всём датасете до train/test split?",
        "hint_en": "Information from test data can influence preprocessing.",
        "hint_ru": "Информация из test может попасть в предобработку.",
        "answer_en": "This creates data leakage: statistics from the test set influence the scaler. The correct approach is to split first, fit the scaler only on train, and transform train and test separately, preferably inside a Pipeline.",
        "answer_ru": "Это создаёт утечку данных: статистики test влияют на scaler. Правильно сначала сделать split, обучить scaler только на train и отдельно трансформировать train/test, лучше внутри Pipeline.",
        "mini_task_en": "Rewrite preprocessing using Pipeline with StandardScaler and LogisticRegression.",
        "mini_task_ru": "Перепиши предобработку через Pipeline со StandardScaler и LogisticRegression.",
    },
    {
        "id": 4,
        "topic": "Train/Test Split",
        "difficulty": "Medium",
        "learning_type": "Time Series",
        "question_en": "Why should you avoid shuffle=True when splitting time series data?",
        "question_ru": "Почему во временных рядах нельзя использовать shuffle=True при разделении данных?",
        "hint_en": "Future observations must not help predict the past.",
        "hint_ru": "Будущие наблюдения не должны помогать предсказывать прошлое.",
        "answer_en": "Shuffling destroys chronological order and can leak future information into training. For time series, use the earlier period for training and the later period for testing.",
        "answer_ru": "Перемешивание разрушает временной порядок и может добавить информацию из будущего в обучение. Для временных рядов train должен быть раньше, test — позже.",
        "mini_task_en": "Write code for a time-based split without shuffling.",
        "mini_task_ru": "Напиши код для временного split без перемешивания.",
    },
    {
        "id": 5,
        "topic": "Metrics",
        "difficulty": "Medium",
        "learning_type": "Classification",
        "question_en": "Why can accuracy be misleading when classes are imbalanced?",
        "question_ru": "Почему accuracy может обманывать при дисбалансе классов?",
        "hint_en": "A model can predict only the majority class and still look good.",
        "hint_ru": "Модель может предсказывать только частый класс и выглядеть хорошей.",
        "answer_en": "Accuracy may be high if the model predicts the majority class, while it fails to detect the minority class. Use precision, recall, F1-score, ROC-AUC/PR-AUC, and confusion matrix.",
        "answer_ru": "Accuracy может быть высокой, если модель предсказывает только самый частый класс, но плохо находит редкий класс. Нужно смотреть precision, recall, F1, ROC-AUC/PR-AUC и confusion matrix.",
        "mini_task_en": "For an imbalanced dataset, compare accuracy and F1-score.",
        "mini_task_ru": "На несбалансированном датасете сравни accuracy и F1-score.",
    },
    {
        "id": 6,
        "topic": "RMSE",
        "difficulty": "Easy",
        "learning_type": "Regression",
        "question_en": "How do you calculate RMSE correctly from true and predicted values?",
        "question_ru": "Как правильно посчитать RMSE по истинным и предсказанным значениям?",
        "hint_en": "RMSE is the square root of mean squared error.",
        "hint_ru": "RMSE — это квадратный корень из MSE.",
        "answer_en": "RMSE = sqrt(mean((y_true - y_pred)^2)). In sklearn, use mean_squared_error(y_true, y_pred) and then take the square root, or use root_mean_squared_error if available.",
        "answer_ru": "RMSE = sqrt(mean((y_true - y_pred)^2)). В sklearn можно использовать mean_squared_error(y_true, y_pred), а потом взять корень, либо root_mean_squared_error, если функция доступна.",
        "mini_task_en": "Write a function that receives y_true and y_pred and returns RMSE.",
        "mini_task_ru": "Напиши функцию, которая принимает y_true и y_pred и возвращает RMSE.",
    },
    {
        "id": 7,
        "topic": "Clustering",
        "difficulty": "Medium",
        "learning_type": "Unsupervised Learning",
        "question_en": "Why should features usually be scaled before K-Means?",
        "question_ru": "Почему перед K-Means обычно нужно масштабировать признаки?",
        "hint_en": "K-Means is distance-based.",
        "hint_ru": "K-Means основан на расстояниях.",
        "answer_en": "K-Means uses distances, so features with larger scales dominate the clustering result. Scaling gives features comparable influence.",
        "answer_ru": "K-Means использует расстояния, поэтому признаки с большим масштабом начинают доминировать. Масштабирование делает вклад признаков сопоставимым.",
        "mini_task_en": "Run K-Means before and after StandardScaler and compare silhouette score.",
        "mini_task_ru": "Запусти K-Means до и после StandardScaler и сравни silhouette score.",
    },
    {
        "id": 8,
        "topic": "PCA",
        "difficulty": "Medium",
        "learning_type": "Unsupervised Learning",
        "question_en": "PCA shows that PC1 and PC2 explain 39% of variance. Can you make final conclusions only from this 2D plot?",
        "question_ru": "PCA показывает, что PC1 и PC2 объясняют 39% дисперсии. Можно ли делать окончательные выводы только по 2D-графику?",
        "hint_en": "The plot shows only part of the information.",
        "hint_ru": "График показывает только часть информации.",
        "answer_en": "No. The first two components explain only part of the variance, so the plot is useful for exploration but not enough for final conclusions. Check more components, metrics, and feature profiles.",
        "answer_ru": "Нет. Первые две компоненты объясняют только часть дисперсии, поэтому график полезен для исследования, но недостаточен для окончательных выводов. Нужно смотреть другие компоненты, метрики и профили признаков.",
        "mini_task_en": "Plot cumulative explained variance and decide how many components to keep.",
        "mini_task_ru": "Построй график накопленной объяснённой дисперсии и реши, сколько компонент оставить.",
    },
    {
        "id": 9,
        "topic": "Time Series",
        "difficulty": "Hard",
        "learning_type": "Time Series",
        "question_en": "Why is rolling mean leakage possible in time series feature engineering?",
        "question_ru": "Почему при создании rolling mean во временных рядах возможна утечка данных?",
        "hint_en": "The current target value must not be used to predict itself.",
        "hint_ru": "Текущее значение target не должно использоваться для предсказания самого себя.",
        "answer_en": "If rolling mean includes the current value, the feature uses information from the target being predicted. Use shift(1) before rolling so only past values are used.",
        "answer_ru": "Если rolling mean включает текущее значение, признак использует информацию о target, который предсказывается. Нужно сначала сделать shift(1), а потом rolling, чтобы использовать только прошлые значения.",
        "mini_task_en": "Create lag and rolling features with shift(1).",
        "mini_task_ru": "Создай лаги и rolling-признаки через shift(1).",
    },
    {
        "id": 10,
        "topic": "Pandas",
        "difficulty": "Easy",
        "learning_type": "General ML",
        "question_en": "You get KeyError: 'lag_1'. What should you check first?",
        "question_ru": "Ты получила KeyError: 'lag_1'. Что проверить в первую очередь?",
        "hint_en": "The column may not exist yet.",
        "hint_ru": "Колонка могла ещё не быть создана.",
        "answer_en": "Check df.columns, verify that the feature creation function was executed, and make sure the column name is spelled correctly. In notebooks, also check the order of executed cells.",
        "answer_ru": "Проверить df.columns, убедиться, что функция создания признаков была выполнена, и проверить правильность имени колонки. В ноутбуке также проверить порядок выполнения ячеек.",
        "mini_task_en": "Create lag_1, lag_2, lag_3 columns using shift().",
        "mini_task_ru": "Создай колонки lag_1, lag_2, lag_3 через shift().",
    },
    {
        "id": 11,
        "topic": "Pipeline",
        "difficulty": "Medium",
        "learning_type": "Supervised Learning",
        "question_en": "Why is sklearn Pipeline useful for ML projects?",
        "question_ru": "Почему sklearn Pipeline полезен в ML-проектах?",
        "hint_en": "It keeps preprocessing and model training together.",
        "hint_ru": "Он объединяет предобработку и обучение модели.",
        "answer_en": "Pipeline makes preprocessing reproducible, reduces data leakage risk, and allows cross-validation to apply transformations correctly inside each fold.",
        "answer_ru": "Pipeline делает предобработку воспроизводимой, снижает риск утечки данных и позволяет правильно применять трансформации внутри каждого фолда при кросс-валидации.",
        "mini_task_en": "Build a Pipeline with StandardScaler and Ridge or LogisticRegression.",
        "mini_task_ru": "Собери Pipeline со StandardScaler и Ridge или LogisticRegression.",
    },
    {
        "id": 12,
        "topic": "Baseline",
        "difficulty": "Easy",
        "learning_type": "General ML",
        "question_en": "Why should you compare a trained model with a baseline?",
        "question_ru": "Зачем сравнивать обученную модель с baseline?",
        "hint_en": "A model is useful only if it beats a simple rule.",
        "hint_ru": "Модель полезна только если она лучше простого правила.",
        "answer_en": "A baseline shows whether the model adds value beyond a simple rule, such as predicting the mean, majority class, or previous time value.",
        "answer_ru": "Baseline показывает, даёт ли модель пользу по сравнению с простым правилом: средним значением, самым частым классом или предыдущим значением временного ряда.",
        "mini_task_en": "Create baseline predictions for regression, classification, and time series.",
        "mini_task_ru": "Создай baseline-прогнозы для регрессии, классификации и временного ряда.",
    },
    {
        "id": 13,
        "topic": "Classification",
        "difficulty": "Medium",
        "learning_type": "Classification",
        "question_en": "What is the difference between precision and recall?",
        "question_ru": "В чём разница между precision и recall?",
        "hint_en": "Precision is about correctness of positive predictions; recall is about finding positives.",
        "hint_ru": "Precision — про точность положительных предсказаний, recall — про нахождение положительных объектов.",
        "answer_en": "Precision answers: among predicted positives, how many are truly positive? Recall answers: among all real positives, how many did the model find?",
        "answer_ru": "Precision отвечает: среди предсказанных положительных сколько действительно положительные? Recall отвечает: среди всех настоящих положительных сколько модель нашла?",
        "mini_task_en": "Calculate precision and recall from a confusion matrix.",
        "mini_task_ru": "Посчитай precision и recall по confusion matrix.",
    },
    {
        "id": 14,
        "topic": "Feature Engineering",
        "difficulty": "Medium",
        "learning_type": "Supervised Learning",
        "question_en": "Why should you create features using training data logic only?",
        "question_ru": "Почему признаки нужно создавать так, чтобы логика не использовала будущую или тестовую информацию?",
        "hint_en": "Features must be available at prediction time.",
        "hint_ru": "Признаки должны быть доступны в момент предсказания.",
        "answer_en": "If a feature uses future or test information, model evaluation becomes unrealistically optimistic. Features should use only information available before prediction.",
        "answer_ru": "Если признак использует будущую или тестовую информацию, оценка модели становится нереалистично хорошей. Признаки должны использовать только информацию, доступную до предсказания.",
        "mini_task_en": "Review a feature list and mark which features can cause leakage.",
        "mini_task_ru": "Проверь список признаков и отметь, какие могут вызвать утечку данных.",
    },
    {
        "id": 15,
        "topic": "Clustering",
        "difficulty": "Hard",
        "learning_type": "Unsupervised Learning",
        "question_en": "Why are clusters not the same as true classes?",
        "question_ru": "Почему кластеры не равны настоящим классам?",
        "hint_en": "Clustering discovers patterns based on selected features and distance rules.",
        "hint_ru": "Кластеризация ищет паттерны по выбранным признакам и правилу расстояния.",
        "answer_en": "Clusters are groups found by an algorithm based on features and distance assumptions. They may or may not match real-world categories, so they must be interpreted and validated carefully.",
        "answer_ru": "Кластеры — это группы, найденные алгоритмом на основе признаков и предположений о расстоянии. Они могут совпадать или не совпадать с реальными категориями, поэтому их нужно осторожно интерпретировать и проверять.",
        "mini_task_en": "Profile clusters by mean feature values and write a cautious interpretation.",
        "mini_task_ru": "Опиши кластеры через средние значения признаков и сформулируй осторожную интерпретацию.",
    },
    {
        "id": 16,
        "topic": "Cross-validation",
        "difficulty": "Medium",
        "learning_type": "Supervised Learning",
        "question_en": "Why is TimeSeriesSplit different from regular KFold?",
        "question_ru": "Чем TimeSeriesSplit отличается от обычного KFold?",
        "hint_en": "Time order is preserved.",
        "hint_ru": "Временной порядок сохраняется.",
        "answer_en": "TimeSeriesSplit preserves chronological order, so validation data always comes after training data. Regular KFold can mix past and future observations.",
        "answer_ru": "TimeSeriesSplit сохраняет хронологический порядок: validation всегда идёт после train. Обычный KFold может перемешать прошлые и будущие наблюдения.",
        "mini_task_en": "Draw or print train/validation indices for TimeSeriesSplit.",
        "mini_task_ru": "Нарисуй или выведи индексы train/validation для TimeSeriesSplit.",
    },
    {
        "id": 17,
        "topic": "NLP",
        "difficulty": "Medium",
        "learning_type": "NLP",
        "question_en": "Why should TF-IDF be fitted only on the training data?",
        "question_ru": "Почему TF-IDF нужно обучать только на train-данных?",
        "hint_en": "Vocabulary and IDF statistics should not know test documents.",
        "hint_ru": "Словарь и IDF-статистики не должны знать test-документы.",
        "answer_en": "Fitting TF-IDF on all data leaks information from test texts into training. Fit vectorizer on train and transform test with the fitted vectorizer.",
        "answer_ru": "Если обучить TF-IDF на всех данных, информация из test-текстов попадёт в обучение. Нужно fit на train и transform на test.",
        "mini_task_en": "Build a text classification Pipeline with TfidfVectorizer and LogisticRegression.",
        "mini_task_ru": "Собери Pipeline для классификации текста с TfidfVectorizer и LogisticRegression.",
    },
    {
        "id": 18,
        "topic": "EDA",
        "difficulty": "Easy",
        "learning_type": "General ML",
        "question_en": "What should you check before choosing an ML model?",
        "question_ru": "Что нужно проверить до выбора ML-модели?",
        "hint_en": "Start with data and task definition.",
        "hint_ru": "Начинай с данных и определения задачи.",
        "answer_en": "Check task goal, target variable, data types, missing values, duplicates, class balance or target distribution, and whether the problem is supervised or unsupervised.",
        "answer_ru": "Проверить цель задачи, target, типы данных, пропуски, дубликаты, баланс классов или распределение target и понять, задача с учителем или без учителя.",
        "mini_task_en": "Create an EDA checklist for a new tabular dataset.",
        "mini_task_ru": "Создай EDA-чек-лист для нового табличного датасета.",
    },
]


def get_topics() -> list[str]:
    return sorted({item["topic"] for item in PRACTICE_TESTS})


def get_difficulties() -> list[str]:
    return ["All", "Easy", "Medium", "Hard"]
